services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.83.0
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "55681:55681"
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    command:
      --config /etc/otel-config.yaml

  jaeger:
    image: jaegertracing/all-in-one:1.41
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
